name: Release
on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build-arcvm-kernel:
    uses: ./.github/workflows/build-kernel-arcvm.yml
    secrets: inherit
  release:
    needs:
      - build-arcvm-kernel
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v8
      - name: Zip ChromeOS ARCVM kernel
        run: |
          for dir in kernel-ARCVM-*; do
            if [ -d "$dir" ]; then
              echo "------ Zip $dir ----------"
              (cd $dir && zip -r9 "$dir".zip ./* -x .git .gitignore ./*.zip && mv *.zip ..)
            fi
          done

      - name: Display structure of downloaded files
        run: ls -R

      - name: release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            kernel-ARCVM*.zip
