name: Release
on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build-arcvm-kernel:
    uses: ./.github/workflows/build-kernel-arcvm.yml
    secrets: inherit
  release:
    needs:
      - build-arcvm-kernel
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v8
      - name: release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            Image